FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    libgomp1 \
    curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN chmod +x start.sh

ENV PYTHONPATH=/app
ENV LLM_PROVIDER=groq
ENV DB_PATH=/app/database/retail.db

RUN mkdir -p /app/faiss_index /app/data/processed /app/data/raw /app/database

EXPOSE 10000

CMD ["./start.sh"]